### ISSUE TITLE
Trying to silence an alert results in CORS error

### ISSUE THREAD

**Issue by dparv** [canonical/karma-k8s-operator#30]
### Bug Description

Posting the silence towards alertmanager results in CORS error on the browser:

![image](https://github.com/canonical/karma-k8s-operator/assets/42830406/41f24c83-c6e3-4540-95dd-56f74f3cb69d)

We need to be able to add to the charm config:

```
  cors:
    allowedOrigins: list of strings
```

### To Reproduce

juju deploy karma-k8s
try to silence an alert on alertmanager

### Environment

edge

### Relevant log output

```shell
N/A
```

**Comment by sed-i** [comment]
@dparv would you be able to add to the issue description:
- output of `juju status --relations`
- contents of the karma config file you attempted

Are you using `proxy: true` in the karma config file? I wonder if it could help.

**Comment by dparv** [comment]
workaround this by a nginx server in the middle between cos and customer endpoint:
```
	location /cos-alertmanager-customer {
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    add_header 'Access-Control-Allow-Origin' '*';
	    proxy_pass http://IP:PORT/cos-alertmanager;
	}
```

**Comment by sed-i** [comment]
Is customer alertmanager a juju relation?
If not, check out https://github.com/canonical/karma-alertmanager-proxy-k8s-operator/

**Comment by dparv** [comment]
We are already using the karma-alertmanager-proxy-k8s to relate customer alertmanagers to karma, which works. The problem is, that Karma posting to silence on the customer alertmanager hits CORS error, so we are using an nginx on :8080 that serves:

1. karma trough the service IP on microk8s for karma pod
2. customer remote alertmanager

so that both are on the same FQDN and the silence works.

**Comment by sed-i** [comment]
In the [docs](https://github.com/prymitive/karma/blob/main/docs/CONFIGURATION.md#listen) it says:

> An empty list means all origins are allowed.

and the the default is an empty list.

---

Karma v0.114 doesn't accept `cors` under `listen`.
```
- Start service "karma" (cannot start service: exited quickly with code 1)
----- Logs from task 0 -----
2023-07-27T20:55:22Z INFO Service "karma" has never been started.
----- Logs from task 1 -----
2023-07-27T20:55:22Z INFO Most recent service output:
    level=fatal msg="Execution failed" error="failed to parse configuration file \"/srv/karma.yaml\": yaml: unmarshal errors:\n  line 7: field cors not found in type struct { Address string; Timeout struct { Read time.Duration; Write time.Duration }; TLS struct { Cert string; Key string }; Port int; Prefix string }"
```

Will play with `proxy: true` next.
