### ISSUE TITLE
`failed to verify` Let's Encrypt certificate

### ISSUE THREAD

**Issue by mthaddon** [canonical/karma-k8s-operator#41]
We've added a Let's Encrypt TLS cert to an internal COS deployment, but we're getting a `Get "https://$hostname/$model-alertmanager/api/v2/status": tls: failed to verify certificate: x509: certificate signed by unknown authority` message from https://$hostname/$model-karma/?q=. It looks like the OCI image used by karma might be missing the ca-certificates package.

**Comment by lucabello** [comment]
This issue should now be fixed, as the Karma rock [does include ca-certs now](https://github.com/canonical/karma-rock/blob/b1fa957d973657883b6b40a41db1326a4b420278/0.120/rockcraft.yaml#L48-L50).

Please feel free to reopen if the issue reoccurs!
